export type IndexTag = "EGX30" | "EGX70" | "EGX100";

export type Stock = {
  symbol: string; // EGX ticker e.g. COMI
  suffix: string; // COMI.CA
  tv: string; // TradingView symbol
  nameEn: string;
  nameAr: string;
  nameEs: string;
  sector: string;
  sectorAr: string;
  sectorEs: string;
  indices: IndexTag[];
  price: number; // reference EGP price
  changePct: number; // reference daily change %
  volume: number; // reference session volume
  support: number;
  resistance: number;
};

export const STOCKS: Stock[] = [
  {
    symbol: "COMI",
    suffix: "COMI.CA",
    tv: "EGX:COMI",
    nameEn: "Commercial International Bank",
    nameAr: "البنك التجاري الدولي",
    nameEs: "Banco Comercial Internacional",
    sector: "Banks",
    sectorAr: "البنوك",
    sectorEs: "Bancos",
    indices: ["EGX30", "EGX100"],
    price: 140.3,
    changePct: 1.24,
    volume: 6_420_000,
    support: 134.8,
    resistance: 146.5,
  },
  {
    symbol: "HRHO",
    suffix: "HRHO.CA",
    tv: "EGX:HRHO",
    nameEn: "EFG Holding",
    nameAr: "المجموعة المالية هيرميس",
    nameEs: "EFG Holding",
    sector: "Financials",
    sectorAr: "الخدمات المالية",
    sectorEs: "Servicios financieros",
    indices: ["EGX30", "EGX100"],
    price: 26.85,
    changePct: -0.72,
    volume: 18_900_000,
    support: 25.4,
    resistance: 28.9,
  },
  {
    symbol: "FWRY",
    suffix: "FWRY.CA",
    tv: "EGX:FWRY",
    nameEn: "Fawry Banking Technology",
    nameAr: "فوري لتكنولوجيا البنوك",
    nameEs: "Fawry Tecnología Bancaria",
    sector: "Technology",
    sectorAr: "التكنولوجيا",
    sectorEs: "Tecnología",
    indices: ["EGX30", "EGX100"],
    price: 7.42,
    changePct: 2.06,
    volume: 41_300_000,
    support: 6.95,
    resistance: 7.98,
  },
  {
    symbol: "SWDY",
    suffix: "SWDY.CA",
    tv: "EGX:SWDY",
    nameEn: "Elsewedy Electric",
    nameAr: "السويدي إليكتريك",
    nameEs: "Elsewedy Electric",
    sector: "Industrials",
    sectorAr: "الصناعة",
    sectorEs: "Industria",
    indices: ["EGX30", "EGX100"],
    price: 89.6,
    changePct: 0.58,
    volume: 5_120_000,
    support: 85.2,
    resistance: 94.4,
  },
  {
    symbol: "ABUK",
    suffix: "ABUK.CA",
    tv: "EGX:ABUK",
    nameEn: "Abu Qir Fertilizers",
    nameAr: "أبو قير للأسمدة",
    nameEs: "Fertilizantes Abu Qir",
    sector: "Chemicals",
    sectorAr: "الكيماويات",
    sectorEs: "Químicos",
    indices: ["EGX30", "EGX100"],
    price: 62.15,
    changePct: -1.35,
    volume: 3_480_000,
    support: 59.3,
    resistance: 66.0,
  },
  {
    symbol: "TMGH",
    suffix: "TMGH.CA",
    tv: "EGX:TMGH",
    nameEn: "Talaat Moustafa Group",
    nameAr: "مجموعة طلعت مصطفى",
    nameEs: "Grupo Talaat Moustafa",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Inmobiliario",
    indices: ["EGX30", "EGX100"],
    price: 54.7,
    changePct: 1.88,
    volume: 12_750_000,
    support: 51.6,
    resistance: 58.2,
  },
  {
    symbol: "ETEL",
    suffix: "ETEL.CA",
    tv: "EGX:ETEL",
    nameEn: "Telecom Egypt",
    nameAr: "المصرية للاتصالات",
    nameEs: "Telecom Egipto",
    sector: "Telecom",
    sectorAr: "الاتصالات",
    sectorEs: "Telecomunicaciones",
    indices: ["EGX30", "EGX100"],
    price: 38.9,
    changePct: 0.31,
    volume: 7_640_000,
    support: 36.8,
    resistance: 41.5,
  },
  {
    symbol: "EAST",
    suffix: "EAST.CA",
    tv: "EGX:EAST",
    nameEn: "Eastern Company",
    nameAr: "الشرقية إيسترن كومباني",
    nameEs: "Eastern Company",
    sector: "Consumer",
    sectorAr: "السلع الاستهلاكية",
    sectorEs: "Consumo",
    indices: ["EGX30", "EGX100"],
    price: 74.25,
    changePct: -0.44,
    volume: 4_210_000,
    support: 71.0,
    resistance: 78.6,
  },
  {
    symbol: "AMOC",
    suffix: "AMOC.CA",
    tv: "EGX:AMOC",
    nameEn: "Alexandria Mineral Oils",
    nameAr: "الإسكندرية للزيوت المعدنية",
    nameEs: "Aceites Minerales Alejandría",
    sector: "Energy",
    sectorAr: "الطاقة",
    sectorEs: "Energía",
    indices: ["EGX30", "EGX100"],
    price: 11.35,
    changePct: 3.12,
    volume: 22_400_000,
    support: 10.4,
    resistance: 12.4,
  },
  {
    symbol: "ORAS",
    suffix: "ORAS.CA",
    tv: "EGX:ORAS",
    nameEn: "Orascom Construction",
    nameAr: "أوراسكوم كونستراكشون",
    nameEs: "Orascom Construction",
    sector: "Industrials",
    sectorAr: "الصناعة",
    sectorEs: "Industria",
    indices: ["EGX30", "EGX100"],
    price: 172.4,
    changePct: 0.92,
    volume: 1_180_000,
    support: 164.5,
    resistance: 181.0,
  },
  {
    symbol: "PHDC",
    suffix: "PHDC.CA",
    tv: "EGX:PHDC",
    nameEn: "Palm Hills Developments",
    nameAr: "بالم هيلز للتعمير",
    nameEs: "Palm Hills Developments",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Inmobiliario",
    indices: ["EGX70", "EGX100"],
    price: 9.86,
    changePct: 2.44,
    volume: 34_100_000,
    support: 9.1,
    resistance: 10.7,
  },
  {
    symbol: "BTFH",
    suffix: "BTFH.CA",
    tv: "EGX:BTFH",
    nameEn: "Beltone Financial Holding",
    nameAr: "بلتون المالية القابضة",
    nameEs: "Beltone Financial Holding",
    sector: "Financials",
    sectorAr: "الخدمات المالية",
    sectorEs: "Servicios financieros",
    indices: ["EGX70", "EGX100"],
    price: 3.94,
    changePct: -2.11,
    volume: 58_600_000,
    support: 3.6,
    resistance: 4.35,
  },
  {
    symbol: "ARAB",
    suffix: "ARAB.CA",
    tv: "EGX:ARAB",
    nameEn: "Arab Developers Holding",
    nameAr: "المطورين العرب القابضة",
    nameEs: "Arab Developers Holding",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Inmobiliario",
    indices: ["EGX70", "EGX100"],
    price: 2.18,
    changePct: 1.4,
    volume: 46_200_000,
    support: 1.98,
    resistance: 2.44,
  },
  {
    symbol: "OIH",
    suffix: "OIH.CA",
    tv: "EGX:OIH",
    nameEn: "Orascom Investment Holding",
    nameAr: "أوراسكوم للاستثمار القابضة",
    nameEs: "Orascom Investment Holding",
    sector: "Holding",
    sectorAr: "شركات قابضة",
    sectorEs: "Holding",
    indices: ["EGX70", "EGX100"],
    price: 1.06,
    changePct: -1.86,
    volume: 88_400_000,
    support: 0.96,
    resistance: 1.18,
  },
  {
    symbol: "MTIE",
    suffix: "MTIE.CA",
    tv: "EGX:MTIE",
    nameEn: "MM Group for Industry",
    nameAr: "إم إم جروب للصناعة",
    nameEs: "MM Group para la Industria",
    sector: "Technology",
    sectorAr: "التكنولوجيا",
    sectorEs: "Tecnología",
    indices: ["EGX70", "EGX100"],
    price: 6.72,
    changePct: 0.75,
    volume: 9_800_000,
    support: 6.2,
    resistance: 7.35,
  },
  {
    symbol: "MFPC",
    suffix: "MFPC.CA",
    tv: "EGX:MFPC",
    nameEn: "Misr Fertilizers Production",
    nameAr: "مصر لإنتاج الأسمدة موبكو",
    nameEs: "Misr Producción de Fertilizantes",
    sector: "Chemicals",
    sectorAr: "الكيماويات",
    sectorEs: "Químicos",
    indices: ["EGX30", "EGX100"],
    price: 118.9,
    changePct: -0.55,
    volume: 1_640_000,
    support: 112.5,
    resistance: 126.0,
  },
  {
    symbol: "JUFO",
    suffix: "JUFO.CA",
    tv: "EGX:JUFO",
    nameEn: "Juhayna Food Industries",
    nameAr: "جهينة للصناعات الغذائية",
    nameEs: "Juhayna Industrias Alimentarias",
    sector: "Consumer",
    sectorAr: "السلع الاستهلاكية",
    sectorEs: "Consumo",
    indices: ["EGX70", "EGX100"],
    price: 21.4,
    changePct: 1.09,
    volume: 3_260_000,
    support: 20.1,
    resistance: 23.0,
  },
  {
    symbol: "SKPC",
    suffix: "SKPC.CA",
    tv: "EGX:SKPC",
    nameEn: "Sidi Kerir Petrochemicals",
    nameAr: "سيدي كرير للبتروكيماويات",
    nameEs: "Petroquímica Sidi Kerir",
    sector: "Chemicals",
    sectorAr: "الكيماويات",
    sectorEs: "Químicos",
    indices: ["EGX70", "EGX100"],
    price: 14.62,
    changePct: -1.02,
    volume: 8_150_000,
    support: 13.8,
    resistance: 15.9,
  },
  {
    symbol: "CIEB",
    suffix: "CIEB.CA",
    tv: "EGX:CIEB",
    nameEn: "Credit Agricole Egypt",
    nameAr: "كريدي أجريكول مصر",
    nameEs: "Credit Agricole Egipto",
    sector: "Banks",
    sectorAr: "البنوك",
    sectorEs: "Bancos",
    indices: ["EGX70", "EGX100"],
    price: 49.3,
    changePct: 0.41,
    volume: 940_000,
    support: 46.9,
    resistance: 52.4,
  },
  {
    symbol: "ESRS",
    suffix: "ESRS.CA",
    tv: "EGX:ESRS",
    nameEn: "Ezz Steel",
    nameAr: "حديد عز",
    nameEs: "Ezz Steel",
    sector: "Resources",
    sectorAr: "الموارد الأساسية",
    sectorEs: "Recursos",
    indices: ["EGX30", "EGX100"],
    price: 84.75,
    changePct: 2.68,
    volume: 5_930_000,
    support: 79.4,
    resistance: 90.6,
  },
  {
    symbol: "EFIH",
    suffix: "EFIH.CA",
    tv: "EGX:EFIH",
    nameEn: "E-Finance for Digital & Financial Investments",
    nameAr: "إي فاينانس للاستثمارات المالية والرقمية",
    nameEs: "E-Finance for Digital & Financial Investments",
    sector: "Technology",
    sectorAr: "التكنولوجيا",
    sectorEs: "Tecnología",
    indices: ["EGX30", "EGX100"],
    price: 13.9,
    changePct: 1.55,
    volume: 1570500,
    support: 13.07,
    resistance: 15.01,
  },
  {
    symbol: "EKHO",
    suffix: "EKHO.CA",
    tv: "EGX:EKHO",
    nameEn: "Egypt Kuwait Holding (USD)",
    nameAr: "القابضة المصرية الكويتية",
    nameEs: "Egypt Kuwait Holding (USD)",
    sector: "Financials",
    sectorAr: "الخدمات المالية",
    sectorEs: "Servicios financieros",
    indices: ["EGX30", "EGX100"],
    price: 1.62,
    changePct: 0.62,
    volume: 403900,
    support: 1.52,
    resistance: 1.75,
  },
  {
    symbol: "KIMA",
    suffix: "KIMA.CA",
    tv: "EGX:KIMA",
    nameEn: "Egyptian Chemical Industries (Kima)",
    nameAr: "كيما للصناعات الكيماوية",
    nameEs: "Egyptian Chemical Industries (Kima)",
    sector: "Chemicals",
    sectorAr: "الكيماويات",
    sectorEs: "Químicos",
    indices: ["EGX30", "EGX100"],
    price: 12.4,
    changePct: -1.11,
    volume: 1428000,
    support: 11.66,
    resistance: 13.39,
  },
  {
    symbol: "MNHD",
    suffix: "MNHD.CA",
    tv: "EGX:MNHD",
    nameEn: "Madinet Masr for Housing & Development",
    nameAr: "مدينة نصر للإسكان والتعمير",
    nameEs: "Madinet Masr for Housing & Development",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX30", "EGX100"],
    price: 6.85,
    changePct: 2.24,
    volume: 900750,
    support: 6.44,
    resistance: 7.4,
  },
  {
    symbol: "HELI",
    suffix: "HELI.CA",
    tv: "EGX:HELI",
    nameEn: "Heliopolis Housing & Development",
    nameAr: "مصر الجديدة للإسكان والتعمير",
    nameEs: "Heliopolis Housing & Development",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX30", "EGX100"],
    price: 9.35,
    changePct: -0.85,
    volume: 1138250,
    support: 8.79,
    resistance: 10.1,
  },
  {
    symbol: "CIRA",
    suffix: "CIRA.CA",
    tv: "EGX:CIRA",
    nameEn: "Cairo Investment & Real Estate Development",
    nameAr: "القاهرة للاستثمار والتنمية العقارية",
    nameEs: "Cairo Investment & Real Estate Development",
    sector: "Education",
    sectorAr: "التعليم",
    sectorEs: "Educación",
    indices: ["EGX30", "EGX100"],
    price: 14.7,
    changePct: 0.95,
    volume: 1646500,
    support: 13.82,
    resistance: 15.88,
  },
  {
    symbol: "AUTO",
    suffix: "AUTO.CA",
    tv: "EGX:AUTO",
    nameEn: "GB Corp",
    nameAr: "جي بي كورب",
    nameEs: "GB Corp",
    sector: "Industrials",
    sectorAr: "الصناعة",
    sectorEs: "Industria",
    indices: ["EGX30", "EGX100"],
    price: 11.8,
    changePct: 1.72,
    volume: 1371000,
    support: 11.09,
    resistance: 12.74,
  },
  {
    symbol: "ISPH",
    suffix: "ISPH.CA",
    tv: "EGX:ISPH",
    nameEn: "Ibnsina Pharma",
    nameAr: "ابن سينا فارما",
    nameEs: "Ibnsina Pharma",
    sector: "Healthcare",
    sectorAr: "الرعاية الصحية",
    sectorEs: "Salud",
    indices: ["EGX30", "EGX100"],
    price: 6.42,
    changePct: 0.78,
    volume: 859900,
    support: 6.03,
    resistance: 6.93,
  },
  {
    symbol: "CCAP",
    suffix: "CCAP.CA",
    tv: "EGX:CCAP",
    nameEn: "Citadel Capital (Qalaa Holdings)",
    nameAr: "القلعة للاستشارات المالية",
    nameEs: "Citadel Capital (Qalaa Holdings)",
    sector: "Financials",
    sectorAr: "الخدمات المالية",
    sectorEs: "Servicios financieros",
    indices: ["EGX30", "EGX100"],
    price: 4.18,
    changePct: -1.42,
    volume: 647100,
    support: 3.93,
    resistance: 4.51,
  },
  {
    symbol: "ORHD",
    suffix: "ORHD.CA",
    tv: "EGX:ORHD",
    nameEn: "Orascom Development Egypt",
    nameAr: "أوراسكوم للتنمية مصر",
    nameEs: "Orascom Development Egypt",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX30", "EGX100"],
    price: 11.25,
    changePct: 1.08,
    volume: 1318750,
    support: 10.57,
    resistance: 12.15,
  },
  {
    symbol: "RAYA",
    suffix: "RAYA.CA",
    tv: "EGX:RAYA",
    nameEn: "Raya Holding for Financial Investments",
    nameAr: "راية القابضة للاستثمارات المالية",
    nameEs: "Raya Holding for Financial Investments",
    sector: "Technology",
    sectorAr: "التكنولوجيا",
    sectorEs: "Tecnología",
    indices: ["EGX30", "EGX100"],
    price: 5.62,
    changePct: 2.35,
    volume: 783900,
    support: 5.28,
    resistance: 6.07,
  },
  {
    symbol: "ORWE",
    suffix: "ORWE.CA",
    tv: "EGX:ORWE",
    nameEn: "Oriental Weavers",
    nameAr: "النساجون الشرقيون",
    nameEs: "Oriental Weavers",
    sector: "Textiles",
    sectorAr: "المنسوجات",
    sectorEs: "Textiles",
    indices: ["EGX30", "EGX100"],
    price: 13.15,
    changePct: 0.55,
    volume: 1499250,
    support: 12.36,
    resistance: 14.2,
  },
  {
    symbol: "ADIB",
    suffix: "ADIB.CA",
    tv: "EGX:ADIB",
    nameEn: "Abu Dhabi Islamic Bank – Egypt",
    nameAr: "مصرف أبوظبي الإسلامي - مصر",
    nameEs: "Abu Dhabi Islamic Bank – Egypt",
    sector: "Banks",
    sectorAr: "البنوك",
    sectorEs: "Bancos",
    indices: ["EGX30", "EGX100"],
    price: 18.6,
    changePct: 1.02,
    volume: 2017000,
    support: 17.48,
    resistance: 20.09,
  },
  {
    symbol: "EGAL",
    suffix: "EGAL.CA",
    tv: "EGX:EGAL",
    nameEn: "Egypt Aluminum",
    nameAr: "مصر للألومنيوم",
    nameEs: "Egypt Aluminum",
    sector: "Basic Resources",
    sectorAr: "الموارد الأساسية",
    sectorEs: "Recursos básicos",
    indices: ["EGX30", "EGX100"],
    price: 64.5,
    changePct: -0.68,
    volume: 6377500,
    support: 60.63,
    resistance: 69.66,
  },
  {
    symbol: "ALCN",
    suffix: "ALCN.CA",
    tv: "EGX:ALCN",
    nameEn: "Alexandria Container & Cargo Handling",
    nameAr: "الإسكندرية لتداول الحاويات",
    nameEs: "Alexandria Container & Cargo Handling",
    sector: "Shipping & Transport",
    sectorAr: "النقل والشحن",
    sectorEs: "Transporte y envío",
    indices: ["EGX70", "EGX100"],
    price: 21.4,
    changePct: 1.18,
    volume: 2283000,
    support: 20.12,
    resistance: 23.11,
  },
  {
    symbol: "AFMC",
    suffix: "AFMC.CA",
    tv: "EGX:AFMC",
    nameEn: "Alexandria Flour Mills",
    nameAr: "مطاحن الإسكندرية",
    nameEs: "Alexandria Flour Mills",
    sector: "Food & Beverage",
    sectorAr: "الأغذية والمشروبات",
    sectorEs: "Alimentos y bebidas",
    indices: ["EGX70", "EGX100"],
    price: 9.85,
    changePct: 0.42,
    volume: 1185750,
    support: 9.26,
    resistance: 10.64,
  },
  {
    symbol: "ACGC",
    suffix: "ACGC.CA",
    tv: "EGX:ACGC",
    nameEn: "Arab Cotton Ginning",
    nameAr: "العربية لحليج الأقطان",
    nameEs: "Arab Cotton Ginning",
    sector: "Textiles",
    sectorAr: "المنسوجات",
    sectorEs: "Textiles",
    indices: ["EGX70", "EGX100"],
    price: 2.34,
    changePct: -0.85,
    volume: 472300,
    support: 2.2,
    resistance: 2.53,
  },
  {
    symbol: "AECT",
    suffix: "AECT.CA",
    tv: "EGX:AECT",
    nameEn: "Arab Engineering & Contracting (Al Ezz)",
    nameAr: "العربية للهندسة والمقاولات",
    nameEs: "Arab Engineering & Contracting (Al Ezz)",
    sector: "Contracting",
    sectorAr: "المقاولات",
    sectorEs: "Contratación",
    indices: ["EGX70", "EGX100"],
    price: 1.92,
    changePct: 1.05,
    volume: 432400,
    support: 1.8,
    resistance: 2.07,
  },
  {
    symbol: "AIND",
    suffix: "AIND.CA",
    tv: "EGX:AIND",
    nameEn: "Arab Aluminum Industry",
    nameAr: "العربية لصناعة الألومنيوم",
    nameEs: "Arab Aluminum Industry",
    sector: "Basic Resources",
    sectorAr: "الموارد الأساسية",
    sectorEs: "Recursos básicos",
    indices: ["EGX70", "EGX100"],
    price: 3.44,
    changePct: 0.58,
    volume: 576800,
    support: 3.23,
    resistance: 3.72,
  },
  {
    symbol: "AIFI",
    suffix: "AIFI.CA",
    tv: "EGX:AIFI",
    nameEn: "Arabia Investments Holding",
    nameAr: "العربية للاستثمارات القابضة",
    nameEs: "Arabia Investments Holding",
    sector: "Financials",
    sectorAr: "الخدمات المالية",
    sectorEs: "Servicios financieros",
    indices: ["EGX70", "EGX100"],
    price: 1.28,
    changePct: -1.15,
    volume: 371600,
    support: 1.2,
    resistance: 1.38,
  },
  {
    symbol: "ALEX",
    suffix: "ALEX.CA",
    tv: "EGX:ALEX",
    nameEn: "Alexandria Mineral & Spinning",
    nameAr: "الإسكندرية للغزل والنسيج",
    nameEs: "Alexandria Mineral & Spinning",
    sector: "Textiles",
    sectorAr: "المنسوجات",
    sectorEs: "Textiles",
    indices: ["EGX70", "EGX100"],
    price: 4.05,
    changePct: 0.74,
    volume: 634750,
    support: 3.81,
    resistance: 4.37,
  },
  {
    symbol: "ALRA",
    suffix: "ALRA.CA",
    tv: "EGX:ALRA",
    nameEn: "Al Arafa Investment & Consulting",
    nameAr: "العرافة للاستثمار والاستشارات",
    nameEs: "Al Arafa Investment & Consulting",
    sector: "Textiles",
    sectorAr: "المنسوجات",
    sectorEs: "Textiles",
    indices: ["EGX70", "EGX100"],
    price: 0.86,
    changePct: 2.38,
    volume: 370000,
    support: 0.81,
    resistance: 0.93,
  },
  {
    symbol: "AMIA",
    suffix: "AMIA.CA",
    tv: "EGX:AMIA",
    nameEn: "Amiral Holding",
    nameAr: "أميرال القابضة",
    nameEs: "Amiral Holding",
    sector: "Industrials",
    sectorAr: "الصناعة",
    sectorEs: "Industria",
    indices: ["EGX70", "EGX100"],
    price: 1.55,
    changePct: 0.65,
    volume: 397250,
    support: 1.46,
    resistance: 1.67,
  },
  {
    symbol: "AMAR",
    suffix: "AMAR.CA",
    tv: "EGX:AMAR",
    nameEn: "Amer Group Holding",
    nameAr: "عامر جروب",
    nameEs: "Amer Group Holding",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 0.62,
    changePct: -1.59,
    volume: 370000,
    support: 0.58,
    resistance: 0.67,
  },
  {
    symbol: "APAX",
    suffix: "APAX.CA",
    tv: "EGX:APAX",
    nameEn: "Ismailia Misr Poultry",
    nameAr: "إسماعيلية مصر للدواجن",
    nameEs: "Ismailia Misr Poultry",
    sector: "Food & Beverage",
    sectorAr: "الأغذية والمشروبات",
    sectorEs: "Alimentos y bebidas",
    indices: ["EGX70", "EGX100"],
    price: 4.62,
    changePct: 1.32,
    volume: 688900,
    support: 4.34,
    resistance: 4.99,
  },
  {
    symbol: "ARCC",
    suffix: "ARCC.CA",
    tv: "EGX:ARCC",
    nameEn: "Arabian Cement",
    nameAr: "العربية للأسمنت",
    nameEs: "Arabian Cement",
    sector: "Building Materials",
    sectorAr: "مواد البناء",
    sectorEs: "Materiales de construcción",
    indices: ["EGX70", "EGX100"],
    price: 9.12,
    changePct: 0.88,
    volume: 1116400,
    support: 8.57,
    resistance: 9.85,
  },
  {
    symbol: "ATQA",
    suffix: "ATQA.CA",
    tv: "EGX:ATQA",
    nameEn: "Misr Beni Suef Cement",
    nameAr: "مصر بني سويف للأسمنت",
    nameEs: "Misr Beni Suef Cement",
    sector: "Building Materials",
    sectorAr: "مواد البناء",
    sectorEs: "Materiales de construcción",
    indices: ["EGX70", "EGX100"],
    price: 42.8,
    changePct: -0.52,
    volume: 4316000,
    support: 40.23,
    resistance: 46.22,
  },
  {
    symbol: "BINV",
    suffix: "BINV.CA",
    tv: "EGX:BINV",
    nameEn: "B Investments Holding",
    nameAr: "بي إنفستمنتس القابضة",
    nameEs: "B Investments Holding",
    sector: "Financials",
    sectorAr: "الخدمات المالية",
    sectorEs: "Servicios financieros",
    indices: ["EGX70", "EGX100"],
    price: 13.2,
    changePct: 1.24,
    volume: 1504000,
    support: 12.41,
    resistance: 14.26,
  },
  {
    symbol: "BIOC",
    suffix: "BIOC.CA",
    tv: "EGX:BIOC",
    nameEn: "Cairo Poultry",
    nameAr: "القاهرة للدواجن",
    nameEs: "Cairo Poultry",
    sector: "Food & Beverage",
    sectorAr: "الأغذية والمشروبات",
    sectorEs: "Alimentos y bebidas",
    indices: ["EGX70", "EGX100"],
    price: 7.05,
    changePct: 0.62,
    volume: 919750,
    support: 6.63,
    resistance: 7.61,
  },
  {
    symbol: "BCSH",
    suffix: "BCSH.CA",
    tv: "EGX:BCSH",
    nameEn: "Bank of Alexandria / Cairo Cotton Center",
    nameAr: "سيتي سنتر للأقطان",
    nameEs: "Bank of Alexandria / Cairo Cotton Center",
    sector: "Industrials",
    sectorAr: "الصناعة",
    sectorEs: "Industria",
    indices: ["EGX70", "EGX100"],
    price: 5.35,
    changePct: -0.95,
    volume: 758250,
    support: 5.03,
    resistance: 5.78,
  },
  {
    symbol: "CERA",
    suffix: "CERA.CA",
    tv: "EGX:CERA",
    nameEn: "Ceramic & Porcelain (Aracemco)",
    nameAr: "الشرقية للسيراميك والبورسلين",
    nameEs: "Ceramic & Porcelain (Aracemco)",
    sector: "Building Materials",
    sectorAr: "مواد البناء",
    sectorEs: "Materiales de construcción",
    indices: ["EGX70", "EGX100"],
    price: 8.24,
    changePct: 1.42,
    volume: 1032800,
    support: 7.75,
    resistance: 8.9,
  },
  {
    symbol: "CLHO",
    suffix: "CLHO.CA",
    tv: "EGX:CLHO",
    nameEn: "Cleopatra Hospital Group",
    nameAr: "مجموعة مستشفيات كليوباترا",
    nameEs: "Cleopatra Hospital Group",
    sector: "Healthcare",
    sectorAr: "الرعاية الصحية",
    sectorEs: "Salud",
    indices: ["EGX70", "EGX100"],
    price: 6.18,
    changePct: 0.98,
    volume: 837100,
    support: 5.81,
    resistance: 6.67,
  },
  {
    symbol: "COAS",
    suffix: "COAS.CA",
    tv: "EGX:COAS",
    nameEn: "Cairo Oils & Soap",
    nameAr: "القاهرة للزيوت والصابون",
    nameEs: "Cairo Oils & Soap",
    sector: "Food & Beverage",
    sectorAr: "الأغذية والمشروبات",
    sectorEs: "Alimentos y bebidas",
    indices: ["EGX70", "EGX100"],
    price: 6.42,
    changePct: -0.72,
    volume: 859900,
    support: 6.03,
    resistance: 6.93,
  },
  {
    symbol: "DACT",
    suffix: "DACT.CA",
    tv: "EGX:DACT",
    nameEn: "Delta Construction & Rebuilding",
    nameAr: "دلتا للإنشاء والتعمير",
    nameEs: "Delta Construction & Rebuilding",
    sector: "Contracting",
    sectorAr: "المقاولات",
    sectorEs: "Contratación",
    indices: ["EGX70", "EGX100"],
    price: 7.68,
    changePct: 1.65,
    volume: 979600,
    support: 7.22,
    resistance: 8.29,
  },
  {
    symbol: "EGBE",
    suffix: "EGBE.CA",
    tv: "EGX:EGBE",
    nameEn: "Egyptian Gulf Bank",
    nameAr: "البنك المصري الخليجي",
    nameEs: "Egyptian Gulf Bank",
    sector: "Banks",
    sectorAr: "البنوك",
    sectorEs: "Bancos",
    indices: ["EGX70", "EGX100"],
    price: 3.72,
    changePct: 0.82,
    volume: 603400,
    support: 3.5,
    resistance: 4.02,
  },
  {
    symbol: "EGCH",
    suffix: "EGCH.CA",
    tv: "EGX:EGCH",
    nameEn: "Egyptian Chemical Industries",
    nameAr: "المصرية للصناعات الكيماوية",
    nameEs: "Egyptian Chemical Industries",
    sector: "Chemicals",
    sectorAr: "الكيماويات",
    sectorEs: "Químicos",
    indices: ["EGX70", "EGX100"],
    price: 5.95,
    changePct: -1.02,
    volume: 815250,
    support: 5.59,
    resistance: 6.43,
  },
  {
    symbol: "EGTS",
    suffix: "EGTS.CA",
    tv: "EGX:EGTS",
    nameEn: "Egyptian for Tourism Resorts",
    nameAr: "المصرية للمنتجعات السياحية",
    nameEs: "Egyptian for Tourism Resorts",
    sector: "Travel & Leisure",
    sectorAr: "السفر والترفيه",
    sectorEs: "Viajes y ocio",
    indices: ["EGX70", "EGX100"],
    price: 2.88,
    changePct: 1.75,
    volume: 523600,
    support: 2.71,
    resistance: 3.11,
  },
  {
    symbol: "EIKU",
    suffix: "EIKU.CA",
    tv: "EGX:EIKU",
    nameEn: "Egyptians Abroad for Investment",
    nameAr: "المصريين بالخارج للاستثمار",
    nameEs: "Egyptians Abroad for Investment",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 1.42,
    changePct: 0.72,
    volume: 384900,
    support: 1.33,
    resistance: 1.53,
  },
  {
    symbol: "EKHOA",
    suffix: "EKHOA.CA",
    tv: "EGX:EKHOA",
    nameEn: "Egypt Kuwait Holding (EGP)",
    nameAr: "القابضة المصرية الكويتية - جنيه",
    nameEs: "Egypt Kuwait Holding (EGP)",
    sector: "Financials",
    sectorAr: "الخدمات المالية",
    sectorEs: "Servicios financieros",
    indices: ["EGX70", "EGX100"],
    price: 78.5,
    changePct: 0.94,
    volume: 7707500,
    support: 73.79,
    resistance: 84.78,
  },
  {
    symbol: "ELKA",
    suffix: "ELKA.CA",
    tv: "EGX:ELKA",
    nameEn: "El Kahera Housing & Development",
    nameAr: "القاهرة للإسكان والتعمير",
    nameEs: "El Kahera Housing & Development",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 5.85,
    changePct: 1.12,
    volume: 805750,
    support: 5.5,
    resistance: 6.32,
  },
  {
    symbol: "ELNA",
    suffix: "ELNA.CA",
    tv: "EGX:ELNA",
    nameEn: "El Nasr Clothing & Textiles (Kabo)",
    nameAr: "النصر للملابس والمنسوجات",
    nameEs: "El Nasr Clothing & Textiles (Kabo)",
    sector: "Textiles",
    sectorAr: "المنسوجات",
    sectorEs: "Textiles",
    indices: ["EGX70", "EGX100"],
    price: 1.18,
    changePct: -0.84,
    volume: 370000,
    support: 1.11,
    resistance: 1.27,
  },
  {
    symbol: "ELSH",
    suffix: "ELSH.CA",
    tv: "EGX:ELSH",
    nameEn: "El Shams Housing & Urbanization",
    nameAr: "الشمس للإسكان والتعمير",
    nameEs: "El Shams Housing & Urbanization",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 1.05,
    changePct: 2.14,
    volume: 370000,
    support: 0.99,
    resistance: 1.13,
  },
  {
    symbol: "EMFD",
    suffix: "EMFD.CA",
    tv: "EGX:EMFD",
    nameEn: "Emaar Misr for Development",
    nameAr: "إعمار مصر للتنمية",
    nameEs: "Emaar Misr for Development",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 4.72,
    changePct: 0.86,
    volume: 698400,
    support: 4.44,
    resistance: 5.1,
  },
  {
    symbol: "MOPCO",
    suffix: "MOPCO.CA",
    tv: "EGX:MOPCO",
    nameEn: "Misr Fertilizers Production (MOPCO)",
    nameAr: "مصر لإنتاج الأسمدة - موبكو",
    nameEs: "Misr Fertilizers Production (MOPCO)",
    sector: "Chemicals",
    sectorAr: "الكيماويات",
    sectorEs: "Químicos",
    indices: ["EGX70", "EGX100"],
    price: 118.4,
    changePct: -0.62,
    volume: 2498000,
    support: 111.3,
    resistance: 127.87,
  },
  {
    symbol: "EQPT",
    suffix: "EQPT.CA",
    tv: "EGX:EQPT",
    nameEn: "Egyptian Transport (Egytrans)",
    nameAr: "المصرية للنقل والتجارة",
    nameEs: "Egyptian Transport (Egytrans)",
    sector: "Shipping & Transport",
    sectorAr: "النقل والشحن",
    sectorEs: "Transporte y envío",
    indices: ["EGX70", "EGX100"],
    price: 18.9,
    changePct: 1.34,
    volume: 2045499,
    support: 17.77,
    resistance: 20.41,
  },
  {
    symbol: "EXPA",
    suffix: "EXPA.CA",
    tv: "EGX:EXPA",
    nameEn: "Export Development Bank of Egypt",
    nameAr: "البنك المصري لتنمية الصادرات",
    nameEs: "Export Development Bank of Egypt",
    sector: "Banks",
    sectorAr: "البنوك",
    sectorEs: "Bancos",
    indices: ["EGX70", "EGX100"],
    price: 12.75,
    changePct: 0.68,
    volume: 1461250,
    support: 11.98,
    resistance: 13.77,
  },
  {
    symbol: "FAIT",
    suffix: "FAIT.CA",
    tv: "EGX:FAIT",
    nameEn: "Faisal Islamic Bank of Egypt",
    nameAr: "بنك فيصل الإسلامي المصري",
    nameEs: "Faisal Islamic Bank of Egypt",
    sector: "Banks",
    sectorAr: "البنوك",
    sectorEs: "Bancos",
    indices: ["EGX70", "EGX100"],
    price: 3.05,
    changePct: 0.55,
    volume: 539750,
    support: 2.87,
    resistance: 3.29,
  },
  {
    symbol: "FIRE",
    suffix: "FIRE.CA",
    tv: "EGX:FIRE",
    nameEn: "Ismailia National Food Industries",
    nameAr: "الإسماعيلية الوطنية للصناعات الغذائية",
    nameEs: "Ismailia National Food Industries",
    sector: "Food & Beverage",
    sectorAr: "الأغذية والمشروبات",
    sectorEs: "Alimentos y bebidas",
    indices: ["EGX70", "EGX100"],
    price: 13.8,
    changePct: -1.22,
    volume: 1561000,
    support: 12.97,
    resistance: 14.9,
  },
  {
    symbol: "GTHE",
    suffix: "GTHE.CA",
    tv: "EGX:GTHE",
    nameEn: "Golden Pyramids Plaza (Cityscape)",
    nameAr: "الأهرامات الذهبية بلازا",
    nameEs: "Golden Pyramids Plaza (Cityscape)",
    sector: "Travel & Leisure",
    sectorAr: "السفر والترفيه",
    sectorEs: "Viajes y ocio",
    indices: ["EGX70", "EGX100"],
    price: 3.62,
    changePct: 0.94,
    volume: 593900,
    support: 3.4,
    resistance: 3.91,
  },
  {
    symbol: "HEAG",
    suffix: "HEAG.CA",
    tv: "EGX:HEAG",
    nameEn: "Heliopolis for Housing (Egypt Gas)",
    nameAr: "مصر للغازات الطبيعية",
    nameEs: "Heliopolis for Housing (Egypt Gas)",
    sector: "Utilities",
    sectorAr: "المرافق",
    sectorEs: "Servicios públicos",
    indices: ["EGX70", "EGX100"],
    price: 21.6,
    changePct: 1.08,
    volume: 2302000,
    support: 20.3,
    resistance: 23.33,
  },
  {
    symbol: "HDBK",
    suffix: "HDBK.CA",
    tv: "EGX:HDBK",
    nameEn: "Housing & Development Bank",
    nameAr: "بنك التعمير والإسكان",
    nameEs: "Housing & Development Bank",
    sector: "Banks",
    sectorAr: "البنوك",
    sectorEs: "Bancos",
    indices: ["EGX70", "EGX100"],
    price: 44.2,
    changePct: 1.45,
    volume: 4449000,
    support: 41.55,
    resistance: 47.74,
  },
  {
    symbol: "IBCT",
    suffix: "IBCT.CA",
    tv: "EGX:IBCT",
    nameEn: "Cairo Educational Services (IBCT)",
    nameAr: "القاهرة للخدمات التعليمية",
    nameEs: "Cairo Educational Services (IBCT)",
    sector: "Education",
    sectorAr: "التعليم",
    sectorEs: "Educación",
    indices: ["EGX70", "EGX100"],
    price: 3.18,
    changePct: 0.62,
    volume: 552100,
    support: 2.99,
    resistance: 3.43,
  },
  {
    symbol: "IDRE",
    suffix: "IDRE.CA",
    tv: "EGX:IDRE",
    nameEn: "Ismailia Misr for Development",
    nameAr: "إسماعيلية مصر للتنمية العقارية",
    nameEs: "Ismailia Misr for Development",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 2.05,
    changePct: -0.78,
    volume: 444750,
    support: 1.93,
    resistance: 2.21,
  },
  {
    symbol: "IFAP",
    suffix: "IFAP.CA",
    tv: "EGX:IFAP",
    nameEn: "International Agricultural Products",
    nameAr: "الدولية للمحاصيل الزراعية",
    nameEs: "International Agricultural Products",
    sector: "Food & Beverage",
    sectorAr: "الأغذية والمشروبات",
    sectorEs: "Alimentos y bebidas",
    indices: ["EGX70", "EGX100"],
    price: 1.72,
    changePct: 1.28,
    volume: 413400,
    support: 1.62,
    resistance: 1.86,
  },
  {
    symbol: "INDP",
    suffix: "INDP.CA",
    tv: "EGX:INDP",
    nameEn: "Industrial Development Group",
    nameAr: "مجموعة التنمية الصناعية",
    nameEs: "Industrial Development Group",
    sector: "Industrials",
    sectorAr: "الصناعة",
    sectorEs: "Industria",
    indices: ["EGX70", "EGX100"],
    price: 1.35,
    changePct: 0.85,
    volume: 378250,
    support: 1.27,
    resistance: 1.46,
  },
  {
    symbol: "ISMA",
    suffix: "ISMA.CA",
    tv: "EGX:ISMA",
    nameEn: "Ismailia Development & Real Estate",
    nameAr: "الإسماعيلية للتنمية العقارية",
    nameEs: "Ismailia Development & Real Estate",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 1.62,
    changePct: -1.05,
    volume: 403900,
    support: 1.52,
    resistance: 1.75,
  },
  {
    symbol: "KABO",
    suffix: "KABO.CA",
    tv: "EGX:KABO",
    nameEn: "El Nasr Clothing (Kabo)",
    nameAr: "كابو للملابس",
    nameEs: "El Nasr Clothing (Kabo)",
    sector: "Textiles",
    sectorAr: "المنسوجات",
    sectorEs: "Textiles",
    indices: ["EGX70", "EGX100"],
    price: 1.24,
    changePct: 1.92,
    volume: 370000,
    support: 1.17,
    resistance: 1.34,
  },
  {
    symbol: "MAER",
    suffix: "MAER.CA",
    tv: "EGX:MAER",
    nameEn: "Maridive & Oil Services",
    nameAr: "ماريديف وخدمات البترول",
    nameEs: "Maridive & Oil Services",
    sector: "Energy",
    sectorAr: "الطاقة",
    sectorEs: "Energía",
    indices: ["EGX70", "EGX100"],
    price: 1.48,
    changePct: 0.72,
    volume: 390600,
    support: 1.39,
    resistance: 1.6,
  },
  {
    symbol: "MPRC",
    suffix: "MPRC.CA",
    tv: "EGX:MPRC",
    nameEn: "Middle East Oil Refinery (Midor)",
    nameAr: "الشرق الأوسط لتكرير البترول",
    nameEs: "Middle East Oil Refinery (Midor)",
    sector: "Energy",
    sectorAr: "الطاقة",
    sectorEs: "Energía",
    indices: ["EGX70", "EGX100"],
    price: 22.4,
    changePct: -0.65,
    volume: 2378000,
    support: 21.06,
    resistance: 24.19,
  },
  {
    symbol: "MPCO",
    suffix: "MPCO.CA",
    tv: "EGX:MPCO",
    nameEn: "Memphis Pharmaceuticals",
    nameAr: "ممفيس للأدوية",
    nameEs: "Memphis Pharmaceuticals",
    sector: "Healthcare",
    sectorAr: "الرعاية الصحية",
    sectorEs: "Salud",
    indices: ["EGX70", "EGX100"],
    price: 9.42,
    changePct: 1.15,
    volume: 1144900,
    support: 8.85,
    resistance: 10.17,
  },
  {
    symbol: "MING",
    suffix: "MING.CA",
    tv: "EGX:MING",
    nameEn: "Misr National Steel (Ataqa)",
    nameAr: "مصر الوطنية للصلب",
    nameEs: "Misr National Steel (Ataqa)",
    sector: "Basic Resources",
    sectorAr: "الموارد الأساسية",
    sectorEs: "Recursos básicos",
    indices: ["EGX70", "EGX100"],
    price: 4.28,
    changePct: 0.92,
    volume: 656600,
    support: 4.02,
    resistance: 4.62,
  },
  {
    symbol: "MOHI",
    suffix: "MOHI.CA",
    tv: "EGX:MOHI",
    nameEn: "Modern Company for Water Proofing",
    nameAr: "الحديثة لمواد العزل",
    nameEs: "Modern Company for Water Proofing",
    sector: "Building Materials",
    sectorAr: "مواد البناء",
    sectorEs: "Materiales de construcción",
    indices: ["EGX70", "EGX100"],
    price: 6.15,
    changePct: -0.85,
    volume: 834250,
    support: 5.78,
    resistance: 6.64,
  },
  {
    symbol: "NAVI",
    suffix: "NAVI.CA",
    tv: "EGX:NAVI",
    nameEn: "Nile Cotton Ginning",
    nameAr: "النيل لحليج الأقطان",
    nameEs: "Nile Cotton Ginning",
    sector: "Textiles",
    sectorAr: "المنسوجات",
    sectorEs: "Textiles",
    indices: ["EGX70", "EGX100"],
    price: 2.62,
    changePct: 1.42,
    volume: 498900,
    support: 2.46,
    resistance: 2.83,
  },
  {
    symbol: "NESR",
    suffix: "NESR.CA",
    tv: "EGX:NESR",
    nameEn: "National Company for Steel (Beshay)",
    nameAr: "الوطنية للحديد والصلب",
    nameEs: "National Company for Steel (Beshay)",
    sector: "Basic Resources",
    sectorAr: "الموارد الأساسية",
    sectorEs: "Recursos básicos",
    indices: ["EGX70", "EGX100"],
    price: 3.85,
    changePct: 0.75,
    volume: 615750,
    support: 3.62,
    resistance: 4.16,
  },
  {
    symbol: "NIPH",
    suffix: "NIPH.CA",
    tv: "EGX:NIPH",
    nameEn: "Nile Pharmaceuticals & Chemical",
    nameAr: "النيل للأدوية والصناعات الكيماوية",
    nameEs: "Nile Pharmaceuticals & Chemical",
    sector: "Healthcare",
    sectorAr: "الرعاية الصحية",
    sectorEs: "Salud",
    indices: ["EGX70", "EGX100"],
    price: 14.6,
    changePct: 0.98,
    volume: 1637000,
    support: 13.72,
    resistance: 15.77,
  },
  {
    symbol: "NSEGB",
    suffix: "NSEGB.CA",
    tv: "EGX:NSEGB",
    nameEn: "National Housing for Professional Syndicates",
    nameAr: "الإسكان الوطني للنقابات المهنية",
    nameEs: "National Housing for Professional Syndicates",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 2.18,
    changePct: 1.24,
    volume: 457100,
    support: 2.05,
    resistance: 2.35,
  },
  {
    symbol: "OCDI",
    suffix: "OCDI.CA",
    tv: "EGX:OCDI",
    nameEn: "SODIC (Six of October Development)",
    nameAr: "السادس من أكتوبر للتنمية - سوديك",
    nameEs: "SODIC (Six of October Development)",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 22.8,
    changePct: 1.55,
    volume: 2416000,
    support: 21.43,
    resistance: 24.62,
  },
  {
    symbol: "PACH",
    suffix: "PACH.CA",
    tv: "EGX:PACH",
    nameEn: "Paints & Chemical Industries (Pachin)",
    nameAr: "الصناعات الكيماوية والدهانات - باكين",
    nameEs: "Paints & Chemical Industries (Pachin)",
    sector: "Chemicals",
    sectorAr: "الكيماويات",
    sectorEs: "Químicos",
    indices: ["EGX70", "EGX100"],
    price: 13.4,
    changePct: -0.72,
    volume: 1523000,
    support: 12.6,
    resistance: 14.47,
  },
  {
    symbol: "PRDC",
    suffix: "PRDC.CA",
    tv: "EGX:PRDC",
    nameEn: "Palm Hills Development / Pioneers Development",
    nameAr: "بايونيرز العقارية",
    nameEs: "Palm Hills Development / Pioneers Development",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 3.92,
    changePct: 1.68,
    volume: 622400,
    support: 3.68,
    resistance: 4.23,
  },
  {
    symbol: "PRCL",
    suffix: "PRCL.CA",
    tv: "EGX:PRCL",
    nameEn: "Pioneers Properties for Urban Development",
    nameAr: "بايونيرز بروبرتيز للتنمية العمرانية",
    nameEs: "Pioneers Properties for Urban Development",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 2.45,
    changePct: 0.88,
    volume: 482750,
    support: 2.3,
    resistance: 2.65,
  },
  {
    symbol: "ROTA",
    suffix: "ROTA.CA",
    tv: "EGX:ROTA",
    nameEn: "Rotafil / Rowad Tourism (Al Rowad)",
    nameAr: "رواد السياحة",
    nameEs: "Rotafil / Rowad Tourism (Al Rowad)",
    sector: "Travel & Leisure",
    sectorAr: "السفر والترفيه",
    sectorEs: "Viajes y ocio",
    indices: ["EGX70", "EGX100"],
    price: 2.14,
    changePct: 1.05,
    volume: 453300,
    support: 2.01,
    resistance: 2.31,
  },
  {
    symbol: "SCEM",
    suffix: "SCEM.CA",
    tv: "EGX:SCEM",
    nameEn: "Sinai Cement",
    nameAr: "أسمنت سيناء",
    nameEs: "Sinai Cement",
    sector: "Building Materials",
    sectorAr: "مواد البناء",
    sectorEs: "Materiales de construcción",
    indices: ["EGX70", "EGX100"],
    price: 22.6,
    changePct: -0.94,
    volume: 2397000,
    support: 21.24,
    resistance: 24.41,
  },
  {
    symbol: "SDTI",
    suffix: "SDTI.CA",
    tv: "EGX:SDTI",
    nameEn: "Sixth of October for Development & Investment",
    nameAr: "السادس من أكتوبر للتنمية والاستثمار",
    nameEs: "Sixth of October for Development & Investment",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 6.35,
    changePct: 1.18,
    volume: 853250,
    support: 5.97,
    resistance: 6.86,
  },
  {
    symbol: "SPIN",
    suffix: "SPIN.CA",
    tv: "EGX:SPIN",
    nameEn: "Egyptian Spinning & Weaving (Spinning)",
    nameAr: "المصرية للغزل والنسيج",
    nameEs: "Egyptian Spinning & Weaving (Spinning)",
    sector: "Textiles",
    sectorAr: "المنسوجات",
    sectorEs: "Textiles",
    indices: ["EGX70", "EGX100"],
    price: 1.08,
    changePct: 0.92,
    volume: 370000,
    support: 1.02,
    resistance: 1.17,
  },
  {
    symbol: "TALM",
    suffix: "TALM.CA",
    tv: "EGX:TALM",
    nameEn: "Taaleem Management Services",
    nameAr: "تعليم لخدمات الإدارة",
    nameEs: "Taaleem Management Services",
    sector: "Education",
    sectorAr: "التعليم",
    sectorEs: "Educación",
    indices: ["EGX70", "EGX100"],
    price: 5.48,
    changePct: 1.35,
    volume: 770600,
    support: 5.15,
    resistance: 5.92,
  },
  {
    symbol: "UEGC",
    suffix: "UEGC.CA",
    tv: "EGX:UEGC",
    nameEn: "Upper Egypt Contracting",
    nameAr: "مقاولات مصر العليا",
    nameEs: "Upper Egypt Contracting",
    sector: "Contracting",
    sectorAr: "المقاولات",
    sectorEs: "Contratación",
    indices: ["EGX70", "EGX100"],
    price: 1.55,
    changePct: -0.82,
    volume: 397250,
    support: 1.46,
    resistance: 1.67,
  },
  {
    symbol: "UNIT",
    suffix: "UNIT.CA",
    tv: "EGX:UNIT",
    nameEn: "United Housing & Development",
    nameAr: "المتحدة للإسكان والتعمير",
    nameEs: "United Housing & Development",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 8.75,
    changePct: 1.12,
    volume: 1081250,
    support: 8.22,
    resistance: 9.45,
  },
  {
    symbol: "VERT",
    suffix: "VERT.CA",
    tv: "EGX:VERT",
    nameEn: "Verdi Group / Egyptian Media Production",
    nameAr: "فيرتي جروب",
    nameEs: "Verdi Group / Egyptian Media Production",
    sector: "Media",
    sectorAr: "الإعلام",
    sectorEs: "Medios",
    indices: ["EGX70", "EGX100"],
    price: 3.28,
    changePct: 0.68,
    volume: 561600,
    support: 3.08,
    resistance: 3.54,
  },
  {
    symbol: "WTSC",
    suffix: "WTSC.CA",
    tv: "EGX:WTSC",
    nameEn: "White Sea Ports Development (Wataniya)",
    nameAr: "تنمية موانئ البحر الأبيض",
    nameEs: "White Sea Ports Development (Wataniya)",
    sector: "Shipping & Transport",
    sectorAr: "النقل والشحن",
    sectorEs: "Transporte y envío",
    indices: ["EGX70", "EGX100"],
    price: 1.95,
    changePct: 1.48,
    volume: 435250,
    support: 1.83,
    resistance: 2.11,
  },
  {
    symbol: "ZMID",
    suffix: "ZMID.CA",
    tv: "EGX:ZMID",
    nameEn: "Zahraa Maadi Investment & Development",
    nameAr: "زهراء المعادي للاستثمار والتعمير",
    nameEs: "Zahraa Maadi Investment & Development",
    sector: "Real Estate",
    sectorAr: "العقارات",
    sectorEs: "Bienes raíces",
    indices: ["EGX70", "EGX100"],
    price: 26.4,
    changePct: 0.85,
    volume: 2758000,
    support: 24.82,
    resistance: 28.51,
  },
];

export const INDEX_TABS = ["ALL", "EGX30", "EGX70", "EGX100", "WATCHLIST"] as const;
export type IndexTab = (typeof INDEX_TABS)[number];

export type Pattern = {
  id: number;
  symbol: string;
  pattern:
    | "bullishEngulfing"
    | "doubleBottom"
    | "ascendingTriangle"
    | "headShoulders"
    | "cupHandle"
    | "fallingWedge";
  confidence: number;
  bias: "bullish" | "bearish";
  timeframe: string;
};

export const PATTERNS: Pattern[] = [
  {
    id: 1,
    symbol: "COMI",
    pattern: "bullishEngulfing",
    confidence: 94,
    bias: "bullish",
    timeframe: "1D",
  },
  {
    id: 2,
    symbol: "TMGH",
    pattern: "ascendingTriangle",
    confidence: 88,
    bias: "bullish",
    timeframe: "1D",
  },
  { id: 3, symbol: "FWRY", pattern: "cupHandle", confidence: 82, bias: "bullish", timeframe: "1W" },
  {
    id: 4,
    symbol: "ABUK",
    pattern: "headShoulders",
    confidence: 79,
    bias: "bearish",
    timeframe: "1D",
  },
  {
    id: 5,
    symbol: "PHDC",
    pattern: "doubleBottom",
    confidence: 86,
    bias: "bullish",
    timeframe: "1D",
  },
  {
    id: 6,
    symbol: "OIH",
    pattern: "headShoulders",
    confidence: 71,
    bias: "bearish",
    timeframe: "1W",
  },
  {
    id: 7,
    symbol: "ESRS",
    pattern: "fallingWedge",
    confidence: 90,
    bias: "bullish",
    timeframe: "1D",
  },
  {
    id: 8,
    symbol: "BTFH",
    pattern: "headShoulders",
    confidence: 68,
    bias: "bearish",
    timeframe: "1D",
  },
  {
    id: 9,
    symbol: "AMOC",
    pattern: "bullishEngulfing",
    confidence: 84,
    bias: "bullish",
    timeframe: "1D",
  },
  {
    id: 10,
    symbol: "SKPC",
    pattern: "doubleBottom",
    confidence: 74,
    bias: "bullish",
    timeframe: "1W",
  },
  {
    id: 11,
    symbol: "ETEL",
    pattern: "ascendingTriangle",
    confidence: 77,
    bias: "bullish",
    timeframe: "1W",
  },
  {
    id: 12,
    symbol: "HRHO",
    pattern: "fallingWedge",
    confidence: 81,
    bias: "bullish",
    timeframe: "1D",
  },
];

/** Deterministic pseudo-random series so charts never "fake tick" between renders. */
export function priceSeries(symbol: string, days: number, endPrice: number, changePct: number) {
  let seed = 0;
  for (let i = 0; i < symbol.length; i++) seed = (seed * 31 + symbol.charCodeAt(i)) % 100000;
  const rand = () => {
    seed = (seed * 1103515245 + 12345) % 2147483648;
    return seed / 2147483648;
  };
  const drift = changePct >= 0 ? 0.00055 : -0.00035;
  const vol = 0.014;
  const values: number[] = [];
  let v = endPrice / (1 + drift * days);
  for (let i = 0; i < days; i++) {
    v = Math.max(0.05, v * (1 + drift + (rand() - 0.5) * vol));
    values.push(v);
  }
  // scale the whole path so it lands exactly on the reference price (no fake final spike)
  const ratio = endPrice / values[values.length - 1];
  for (let i = 0; i < values.length; i++) values[i] *= ratio;
  const now = Date.now();
  const step = 86_400_000;
  return values.map((price, i) => ({
    t: now - (days - 1 - i) * step,
    price: Number(price.toFixed(2)),
  }));
}

export type NewsItem = {
  id: number;
  headline: string;
  headlineAr: string;
  ticker: string;
  date: string;
  verdict: "positive" | "negative" | "neutral";
  summary: string;
};

export const NEWS: NewsItem[] = [
  {
    id: 1,
    headline: "CIB announces higher cash dividend distribution for FY results",
    headlineAr: "البنك التجاري الدولي يعلن توزيعات نقدية أعلى",
    ticker: "COMI.CA",
    date: "Today · 11:20",
    verdict: "positive",
    summary:
      "Higher payout signals strong capital adequacy and typically attracts institutional inflows into the share.",
  },
  {
    id: 2,
    headline: "Fawry reports 38% YoY growth in digital transaction volumes",
    headlineAr: "فوري تسجل نموًا 38% في أحجام المعاملات الرقمية",
    ticker: "FWRY.CA",
    date: "Today · 10:05",
    verdict: "positive",
    summary:
      "Accelerating transaction growth supports margin expansion and justifies a re-rating of the multiple.",
  },
  {
    id: 3,
    headline: "Abu Qir Fertilizers faces temporary gas supply curtailment",
    headlineAr: "أبو قير للأسمدة تواجه خفضًا مؤقتًا في إمدادات الغاز",
    ticker: "ABUK.CA",
    date: "Today · 09:45",
    verdict: "negative",
    summary:
      "Production downtime pressures quarterly volumes and may cap the share near its short-term resistance.",
  },
  {
    id: 4,
    headline: "EGX30 crosses 52,800 points on broad-based buying",
    headlineAr: "المؤشر EGX30 يتجاوز 52,800 نقطة بدعم شراء واسع",
    ticker: "EGX30",
    date: "Today · 13:00",
    verdict: "positive",
    summary:
      "A close above 53,000 would confirm continuation and improve odds of further upside next session.",
  },
  {
    id: 5,
    headline: "Talaat Moustafa Group launches new North Coast phase",
    headlineAr: "مجموعة طلعت مصطفى تطلق مرحلة جديدة بالساحل الشمالي",
    ticker: "TMGH.CA",
    date: "Yesterday · 16:10",
    verdict: "positive",
    summary:
      "Fresh launches strengthen the backlog and support forward revenue visibility for the developer.",
  },
  {
    id: 6,
    headline: "Orascom Investment Holding postpones extraordinary meeting",
    headlineAr: "أوراسكوم للاستثمار تؤجل الجمعية العامة غير العادية",
    ticker: "OIH.CA",
    date: "Yesterday · 14:22",
    verdict: "negative",
    summary:
      "Governance delays add uncertainty and usually keep speculative flows away in the near term.",
  },
  {
    id: 7,
    headline: "Central Bank keeps overnight rates unchanged",
    headlineAr: "البنك المركزي يبقي أسعار العائد دون تغيير",
    ticker: "MACRO",
    date: "Yesterday · 12:00",
    verdict: "neutral",
    summary:
      "A hold keeps bank margins stable while leaving equity valuations broadly unchanged for now.",
  },
  {
    id: 8,
    headline: "Beltone Financial completes capital increase subscription",
    headlineAr: "بلتون المالية تستكمل الاكتتاب في زيادة رأس المال",
    ticker: "BTFH.CA",
    date: "2 days ago",
    verdict: "neutral",
    summary:
      "Additional capital funds expansion but near-term dilution offsets much of the positive impact.",
  },
];

export type EventItem = {
  ticker: string;
  company: string;
  type: "Dividend" | "Coupon" | "AGM" | "Earnings";
  date: string;
  detail: string;
};

export const EVENTS: EventItem[] = [
  {
    ticker: "COMI.CA",
    company: "Commercial International Bank",
    type: "Dividend",
    date: "12 Aug 2026",
    detail: "EGP 1.75 / share cash dividend — ex-date",
  },
  {
    ticker: "ABUK.CA",
    company: "Abu Qir Fertilizers",
    type: "Coupon",
    date: "18 Aug 2026",
    detail: "Second coupon distribution EGP 2.20 / share",
  },
  {
    ticker: "SWDY.CA",
    company: "Elsewedy Electric",
    type: "AGM",
    date: "24 Aug 2026",
    detail: "Ordinary general assembly — FY approvals",
  },
  {
    ticker: "FWRY.CA",
    company: "Fawry",
    type: "Earnings",
    date: "30 Aug 2026",
    detail: "Q2 results release and analyst call",
  },
  {
    ticker: "TMGH.CA",
    company: "Talaat Moustafa Group",
    type: "Dividend",
    date: "03 Sep 2026",
    detail: "EGP 0.65 / share cash dividend — record date",
  },
  {
    ticker: "EAST.CA",
    company: "Eastern Company",
    type: "Coupon",
    date: "09 Sep 2026",
    detail: "Interim coupon EGP 1.10 / share",
  },
  {
    ticker: "HRHO.CA",
    company: "EFG Holding",
    type: "AGM",
    date: "15 Sep 2026",
    detail: "Extraordinary assembly — capital restructuring",
  },
  {
    ticker: "AMOC.CA",
    company: "Alexandria Mineral Oils",
    type: "Earnings",
    date: "21 Sep 2026",
    detail: "Fiscal year results announcement",
  },
];

export const fmt = (n: number, d = 2) =>
  n.toLocaleString("en-US", { minimumFractionDigits: d, maximumFractionDigits: d });
